# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  username: admin
  password: Alpyne2022!
  host: alpynetest-1.cso1aghrpext.us-west-2.rds.amazonaws.com
  port: 3306

development:
  <<: *default
  database: test3-dev

test:
  <<: *default
  database: test3-test

production:
  <<: *default
  database: test3-prod